### ISSUE TITLE
Will Python APIs be provided?

### ISSUE THREAD

**Issue by harupy** [databrickslabs/automl-toolkit#2]
It seems that the current version only supports scala APIs to build automation flow. Will Python APIs be provided?

**Comment by BenWilson2** [comment]
Most definitely.  The Python wrapper API is next on the roadmap and is planned for release as part of either 0.5.3 or 0.5.4.

**Comment by harupy** [comment]
Got it! Thanks!

**Comment by harupy** [comment]
Will all the source code be public?

**Comment by aliL1** [comment]
> Most definitely. The Python wrapper API is next on the roadmap and is planned for release as part of either 0.5.3 or 0.5.4.

I was waiting for this update but this issue is closed now. Do you still have a plan for python wrapper and when is the expected release date? Thank you!

**Comment by BenWilson2** [comment]
We're doing the final testing and reviewing the PR this week.  Stay tuned!

**Comment by aliL1** [comment]
Great!  Thanks!
