### ISSUE TITLE
How to install AutoML-Toolkit for python in databricks?

### ISSUE THREAD

**Issue by jingwora** [databrickslabs/automl-toolkit#20]
This module it very promising.
I want to use it but I dont know how can I get .whl file.

As in python installation document,
Currently, this library exists as a .whl file in the /dist directory. 

Where can find the .whl file and add in Databricks?

Many thanks in advance.

**Comment by nsenno-dbr** [comment]
Hello, 

You should be able to build the .whl from source using `bdist_wheel` as described in the documentation. 

If you continue to have problems please reach out to me directly at nick.senno@databricks.com

**Comment by jingwora** [comment]
Thank you!
From teh documentation, I can install the wheel now.
